# application-h2.yml
spring:
  application:
    name: day2
  datasource:
    url: jdbc:h2:mem:testdb
    #    url: jdbc:h2:file:~/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true